on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: oven-sh/setup-bun@v1
      - run: ls && ls public
      - run: bun install
      - run: bun run build
