on: 
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1

      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun add --dev --exact @biomejs/biome
      - run: biome format src/
      - run: bun run build

